<?php
/**
 * Created by PhpStorm.
 * User: zcluo
 * Date: 2016/6/12
 * Time: 14:49
 */

namespace emmaluo;


class ExtendClass extends SimpleClass
{
    public function displayVar()
    {
        echo "Extending class";
        echo "<br/>";
        parent::displayVar(); // TODO: Change the autogenerated stub
    }

}